---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: europe-west2-docker.pkg.dev/GOOGLE_PROJECT/demo/nginx:latest
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: ekickone-certificate
spec:
  domains:
    - e-kick.one
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ekickone-ingress
  annotations:
    networking.gke.io/managed-certificates: ekickone-certificate
spec:
  rules:
  - host: e-kick.one
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx
            port:
              number: 80