name: Deploy Nginx

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@main
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@main
      with:
        cluster_name: autopilot-prod-cluster
        location: europe-west2
        credentials: ${{ secrets.GCP_SA_KEY }}

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        gcloud auth configure-docker europe-west2-docker.pkg.dev
        docker build -t europe-west2-docker.pkg.dev/$GOOGLE_PROJECT/demo/nginx:latest .
        docker push europe-west2-docker.pkg.dev/$GOOGLE_PROJECT/demo/nginx:latest

    - name: deploy to gke
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        gcloud container clusters get-credentials autopilot-prod-cluster --region europe-west2
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" resources.yaml
        kubectl apply -f resources.yaml
